apiVersion: v1
kind: ServiceAccount
metadata:
  name: shpod
  namespace: shpod
---
apiVersion: v1
kind: Pod
metadata:
  name: shpod
  labels:
    team: service-to-service-fabric
    owner: jbaumont 
  annotations:
    atlassian.com/business_unit: Cloud Platform Engineering
  namespace: shpod
spec:
  serviceAccountName: shpod
  containers:
  - name: shpod
    image: jpetazzo/shpod
    imagePullPolicy: IfNotPresent
    stdin: true
    tty: true
    env:
    - name: HOSTIP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP


